# Generated by Django 3.2.6 on 2021-08-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='author',
            name='birthdate',
        ),
    ]
