# Generated by Django 3.2.6 on 2021-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('rating', models.FloatField()),
                ('publication_year', models.IntegerField()),
                ('authors', models.ManyToManyField(to='author.Author')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
    ]
