# Generated by Django 3.2.6 on 2021-09-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('rating', models.FloatField()),
                ('publication_year', models.IntegerField(default=2021)),
                ('cover_img', models.ImageField(default='book_covers/default.png', upload_to='book_covers')),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='author.Author')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
