# Generated by Django 3.2.6 on 2021-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210816_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.ImageField(default='default.png', upload_to='book_covers'),
        ),
    ]
