# Generated by Django 3.2.6 on 2021-08-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_url',
            new_name='cover_img',
        ),
    ]
