# Generated by Django 3.2.6 on 2021-08-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_image_url_book_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(default='book_covers/default.png', upload_to='book_covers'),
        ),
    ]
