# Generated by Django 3.2.6 on 2021-08-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_cover_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-rating']},
        ),
    ]
