# Generated by Django 3.2.6 on 2021-08-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20210816_1029'),
        ('book', '0007_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='author.Author'),
        ),
    ]
