# Generated by Django 3.2.6 on 2021-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20210816_1029'),
        ('book', '0010_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='author.Author'),
        ),
    ]
