# Generated by Django 3.2.6 on 2021-08-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='empty', max_length=128),
            preserve_default=False,
        ),
    ]
